"""Add HotelRoomPricingFormula table

Revision ID: b2f4b9b11a21
Revises: 
Create Date: 2026-03-13 04:30:11.838421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f4b9b11a21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_room_pricing_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('formula_type', sa.String(length=100), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('round_minutes', sa.Integer(), nullable=True),
    sa.Column('hour_first_count', sa.Integer(), nullable=True),
    sa.Column('hour_first_price', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('hour_next_price', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('night_price', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('night_checkin_time', sa.Time(), nullable=True),
    sa.Column('night_checkout_time', sa.Time(), nullable=True),
    sa.Column('night_start_window', sa.Time(), nullable=True),
    sa.Column('night_end_window', sa.Time(), nullable=True),
    sa.Column('night_extra_fee_per_hour', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('daily_price', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('daily_checkin_time', sa.Time(), nullable=True),
    sa.Column('daily_checkout_time', sa.Time(), nullable=True),
    sa.Column('daily_extra_fee_per_hour', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['hotel_room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotel_room_pricing_formulas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_room_pricing_formulas_room_type_id'), ['room_type_id'], unique=False)
        
    with op.batch_alter_table('hotel_room_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default='2', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_room_types', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    with op.batch_alter_table('hotel_room_pricing_formulas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_room_pricing_formulas_room_type_id'))

    op.drop_table('hotel_room_pricing_formulas')
    # ### end Alembic commands ###
